name: SilentBullWatchApp
options:
  bundleIdPrefix: com.imsec
targets:
  SilentBullWatchApp:
    type: application
    platform: watchOS
    sources: [Sources]
    info:
      path: Info.plist
      version: 1.0
      build: 1

