name: Build Wear OS App

on:
  push:
    paths:
      - 'android-wearos/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
        working-directory: android-wearos

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug
        working-directory: android-wearos

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilentBull-WearOS-Debug-APK
          path: android-wearos/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
