name: Build Watch OS App

on:
  push:
    paths:
      - 'ios-watchos/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build watchOS App
      run: |
        cd ios-watchos
        xcodebuild -project SilentBullWatchApp.xcodeproj \
                   -scheme SilentBullWatchApp \
                   -destination 'generic/platform=watchOS' \
                   clean build

